### ISSUE TITLE
Phosphor icons Unexpected token error

### ISSUE THREAD

**Issue by PabloCorso** [jacobparis-insiders/sly#65]
I'm having an issue when trying to add the `phosphor-icons` package using the `@sly-cli/sly` tool. Not sure if I'm using it right.

Using:
```sh
npx @sly-cli/sly add phosphor-icons sparkle
```

Output:
```
SyntaxError: Unexpected token 'U', "Unexpected"... is not valid JSON
Error: Failed to fetch registry from https://sly-cli.fly.dev.
file:///path/to/project/node_modules/@sly-cli/sly/dist/index.js:288
    throw new Error(`Failed to fetch tree from registry.`);
          ^

Error: Failed to fetch tree from registry.
    at file:///path/to/project/node_modules/@sly-cli/sly/dist/index.js:288:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchTree (file:///path/to/project/node_modules/@sly-cli/sly/dist/index.js:280:18)
    at async Command.<anonymous> (file:///path/to/project/node_modules/@sly-cli/sly/dist/index.js:618:19)
```

**Comment by PabloCorso** [comment]
Good catch, thank you for your help!

**Comment by petephm** [comment]
I'm also getting this issue when trying to add any phosphor-icons.

![image](https://github.com/user-attachments/assets/9043ee72-7c1e-43e8-a42f-f68a7877c974)

**Comment by jacobparis** [comment]
We'll be switching to Iconify as an icon provider, which includes phosphor plus all its variants, will be fixed in #71
